// Réexportation pour compatibilité avec les imports existants
export {
  ANNONCES_MOCK,
  MOCK_LISTINGS,
  TYPES_BIENS,
  PROPERTY_TYPES,
  TYPES_TRANSACTION,
  QUARTIERS,
  DISTRICTS,
  LISTE_EQUIPEMENTS,
  AMENITIES_LIST,
  CONVERSATIONS_MOCK,
  MOCK_CONVERSATIONS,
  NOTIFICATIONS_MOCK,
  MOCK_NOTIFICATIONS,
  AGENTS_MOCK,
  MOCK_AGENTS,
} from './donneesMock';
