import { Bien, Conversation, Notification, Agent } from '../types/modeles';

export const ANNONCES_FICTIVES: Bien[] = [
  {
    id: '1',
    titre: 'Chambre meublée à Adidogomé',
    type: 'Chambre',
    typeTransaction: 'location',
    prix: 25000,
    infoPrix: {
      prixMensuel: 25000,
      avanceMois: 6,
      cautionMois: 3,
      commissionDemarcheur: 25000,
    },
    localisation: 'Adidogomé, Lomé',
    quartier: 'Golfe',
    description: 'Belle chambre meublée avec climatisation, salle de bain privée et accès WiFi. Proche du campus universitaire de Lomé.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600',
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600',
    ],
    videos: [],
    statut: 'disponible',
    chambres: 1,
    sallesDeBain: 1,
    superficie: 15,
    equipements: ['WiFi', 'Climatisation', 'Salle de bain privée', 'Cuisine partagée'],
    agent: {
      id: 'a1',
      nom: 'Kofi Mensah',
      telephone: '+228 90 00 00 01',
      email: 'kofi@logetogo.tg',
      avatar: 'https://i.pravatar.cc/100?img=1',
      note: 4.8,
    },
    note: 4.5,
    avis: 12,
    distance: 0.5,
    coordonnees: { latitude: 6.1726, longitude: 1.2312 },
    creeLe: '2026-02-10',
    vues: 145,
  },
  {
    id: '2',
    titre: 'Studio moderne à Bè',
    type: 'Studio',
    typeTransaction: 'location',
    prix: 45000,
    infoPrix: {
      prixMensuel: 45000,
      avanceMois: 10,
      cautionMois: 6,
      commissionDemarcheur: 45000,
    },
    localisation: 'Bè, Lomé',
    quartier: 'Golfe',
    description: 'Studio entièrement rénové avec salon, cuisine équipée et salle de bain moderne. Quartier animé.',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600',
    ],
    videos: [],
    statut: 'disponible',
    chambres: 1,
    sallesDeBain: 1,
    superficie: 30,
    equipements: ['WiFi', 'Cuisine équipée', 'Parking', 'Sécurité 24/7'],
    agent: {
      id: 'a2',
      nom: 'Ama Koffi',
      telephone: '+228 90 00 00 02',
      email: 'ama@logetogo.tg',
      avatar: 'https://i.pravatar.cc/100?img=5',
      note: 4.9,
    },
    note: 4.7,
    avis: 8,
    distance: 1.2,
    coordonnees: { latitude: 6.1400, longitude: 1.2450 },
    creeLe: '2026-02-12',
    vues: 89,
  },
  {
    id: '3',
    titre: 'Appartement F2 à Tokoin',
    type: 'Appartement',
    typeTransaction: 'location',
    prix: 75000,
    infoPrix: {
      prixMensuel: 75000,
      avanceMois: 12,
      cautionMois: 6,
      commissionDemarcheur: 75000,
    },
    localisation: 'Tokoin, Lomé',
    quartier: 'Golfe',
    description: 'Bel appartement F2 avec terrasse, vue dégagée, quartier calme et sécurisé.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600',
      'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=600',
    ],
    videos: [],
    statut: 'disponible',
    chambres: 2,
    sallesDeBain: 1,
    superficie: 55,
    equipements: ['WiFi', 'Terrasse', 'Parking', 'Climatisation', 'Sécurité'],
    agent: {
      id: 'a3',
      nom: 'Edem Agbo',
      telephone: '+228 90 00 00 03',
      email: 'edem@logetogo.tg',
      avatar: 'https://i.pravatar.cc/100?img=8',
      note: 4.6,
    },
    note: 4.8,
    avis: 20,
    distance: 2.1,
    coordonnees: { latitude: 6.1528, longitude: 1.2176 },
    creeLe: '2026-02-08',
    vues: 210,
  },
  {
    id: '4',
    titre: 'Terrain à bâtir à Agoè',
    type: 'Terrain',
    typeTransaction: 'vente',
    prix: 8500000,
    localisation: 'Agoè-Nyivé, Lomé',
    quartier: 'Agoe',
    description: 'Beau terrain de 500m² avec titre foncier. Quartier en plein développement, accès facile.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600',
    ],
    videos: [],
    statut: 'disponible',
    chambres: 0,
    sallesDeBain: 0,
    superficie: 500,
    equipements: ['Titre foncier', 'Borné', 'Accès route principale'],
    agent: {
      id: 'a1',
      nom: 'Kofi Mensah',
      telephone: '+228 90 00 00 01',
      email: 'kofi@logetogo.tg',
      avatar: 'https://i.pravatar.cc/100?img=1',
      note: 4.8,
    },
    note: 4.2,
    avis: 3,
    distance: 4.5,
    coordonnees: { latitude: 6.2100, longitude: 1.2234 },
    creeLe: '2026-02-15',
    vues: 87,
  },
  {
    id: '5',
    titre: 'Villa 3 chambres à Agoe',
    type: 'Villa',
    typeTransaction: 'location',
    prix: 150000,
    infoPrix: {
      prixMensuel: 150000,
      avanceMois: 12,
      cautionMois: 6,
      commissionDemarcheur: 150000,
    },
    localisation: 'Agoe, Lomé',
    quartier: 'Agoe',
    description: 'Magnifique villa avec jardin privatif, garage et résidence sécurisée.',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600',
    ],
    videos: [],
    statut: 'disponible',
    chambres: 3,
    sallesDeBain: 2,
    superficie: 120,
    equipements: ['Jardin', 'Garage', 'Climatisation', 'Sécurité 24/7', 'WiFi'],
    agent: {
      id: 'a2',
      nom: 'Ama Koffi',
      telephone: '+228 90 00 00 02',
      email: 'ama@logetogo.tg',
      avatar: 'https://i.pravatar.cc/100?img=5',
      note: 4.9,
    },
    note: 4.9,
    avis: 3,
    distance: 4.5,
    coordonnees: { latitude: 6.2100, longitude: 1.2234 },
    creeLe: '2026-02-15',
    vues: 320,
  },
  {
    id: '6',
    titre: 'Maison à vendre à Kodjoviakopé',
    type: 'Villa',
    typeTransaction: 'vente',
    prix: 25000000,
    localisation: 'Kodjoviakopé, Lomé',
    quartier: 'Golfe',
    description: 'Belle maison de 4 pièces à vendre. Titre foncier disponible. Quartier calme et sécurisé.',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600',
    ],
    videos: [],
    statut: 'disponible',
    chambres: 4,
    sallesDeBain: 2,
    superficie: 200,
    equipements: ['Titre foncier', 'Eau courante', 'Électricité', 'Jardin', 'Garage'],
    agent: {
      id: 'a3',
      nom: 'Edem Agbo',
      telephone: '+228 90 00 00 03',
      email: 'edem@logetogo.tg',
      avatar: 'https://i.pravatar.cc/100?img=8',
      note: 4.6,
    },
    note: 4.5,
    avis: 7,
    distance: 0.8,
    coordonnees: { latitude: 6.1375, longitude: 1.2123 },
    creeLe: '2026-02-14',
    vues: 180,
  },
];

export const TYPES_BIENS: string[] = ['Tous', 'Chambre', 'Studio', 'Appartement', 'Villa', 'Bureau', 'Terrain'];
export const TYPES_TRANSACTION: string[] = ['Tous', 'location', 'vente'];
export const QUARTIERS: string[] = ['Tous', 'Golfe', 'Agoe', 'Bè', 'Akébou', 'Atakpamé', 'Kpalimé'];

export const EQUIPEMENTS_LISTE: string[] = [
  'WiFi', 'Climatisation', 'Parking', 'Sécurité 24/7', 'Cuisine équipée',
  'Terrasse', 'Jardin', 'Salle de bain privée', 'Eau courante',
  'Électricité', 'Groupe électrogène', 'Gardien', 'Titre foncier',
  'Borné', 'Piscine', 'Ascenseur',
];

export const AGENTS_FICTIFS: Agent[] = [
  { id: 'a1', nom: 'Kofi Mensah', telephone: '+228 90 00 00 01', email: 'kofi@logetogo.tg', avatar: 'https://i.pravatar.cc/100?img=1', note: 4.8, annonces: 12, avis: 34, verifie: true },
  { id: 'a2', nom: 'Ama Koffi', telephone: '+228 90 00 00 02', email: 'ama@logetogo.tg', avatar: 'https://i.pravatar.cc/100?img=5', note: 4.9, annonces: 8, avis: 21, verifie: true },
  { id: 'a3', nom: 'Edem Agbo', telephone: '+228 90 00 00 03', email: 'edem@logetogo.tg', avatar: 'https://i.pravatar.cc/100?img=8', note: 4.6, annonces: 15, avis: 45, verifie: false },
];

export const CONVERSATIONS_FICTIVES: Conversation[] = [
  {
    id: 'c1',
    idBien: '1',
    titreBien: 'Chambre meublée à Adidogomé',
    autreUtilisateur: { id: 'a1', nom: 'Kofi Mensah', avatar: 'https://i.pravatar.cc/100?img=1', type: 'agent' },
    dernierMessage: 'La chambre est disponible dès maintenant.',
    heureDernierMessage: '10:30',
    nonLus: 2,
    messages: [
      { id: 'm1', envoyeurId: 'moi', texte: 'Bonjour, la chambre est encore disponible?', typeMessage: 'texte', heure: '10:25', lu: true },
      { id: 'm2', envoyeurId: 'a1', texte: 'Bonjour! Oui, elle est disponible.', typeMessage: 'texte', heure: '10:28', lu: true },
      { id: 'm3', envoyeurId: 'a1', texte: 'La chambre est disponible dès maintenant.', typeMessage: 'texte', heure: '10:30', lu: false },
    ],
  },
  {
    id: 'c2',
    idBien: '3',
    titreBien: 'Appartement F2 à Tokoin',
    autreUtilisateur: { id: 'a3', nom: 'Edem Agbo', avatar: 'https://i.pravatar.cc/100?img=8', type: 'agent' },
    dernierMessage: 'Pouvez-vous venir visiter demain?',
    heureDernierMessage: 'Hier',
    nonLus: 0,
    messages: [
      { id: 'm4', envoyeurId: 'moi', texte: 'Je suis intéressé par l\'appartement.', typeMessage: 'texte', heure: 'Hier 14:00', lu: true },
      { id: 'm5', envoyeurId: 'a3', texte: 'Pouvez-vous venir visiter demain?', typeMessage: 'texte', heure: 'Hier 14:15', lu: true },
    ],
  },
];

export const NOTIFICATIONS_FICTIVES: Notification[] = [
  { id: 'n1', type: 'nouvelle_annonce', titre: 'Nouvelle chambre disponible!', corps: 'Une chambre correspondant à vos critères vient d\'être publiée à Adidogomé.', heure: '5 min', lu: false, idBien: '1' },
  { id: 'n2', type: 'message', titre: 'Nouveau message de Kofi Mensah', corps: 'La chambre est disponible dès maintenant.', heure: '10 min', lu: false },
  { id: 'n3', type: 'mise_a_jour_statut', titre: 'Statut mis à jour', corps: 'La chambre que vous suiviez à Djidjolé est maintenant occupée.', heure: '1h', lu: true },
  { id: 'n4', type: 'avis', titre: 'Nouvel avis reçu', corps: 'Vous avez reçu un nouvel avis de 5 étoiles.', heure: '2h', lu: true },
];

// Alias anglais compatibilité
export const MOCK_LISTINGS = ANNONCES_FICTIVES;
export const PROPERTY_TYPES = TYPES_BIENS;
export const DISTRICTS = QUARTIERS;
export const AMENITIES_LIST = EQUIPEMENTS_LISTE;
export const MOCK_AGENTS = AGENTS_FICTIFS;
export const MOCK_CONVERSATIONS = CONVERSATIONS_FICTIVES;
export const MOCK_NOTIFICATIONS = NOTIFICATIONS_FICTIVES;
